In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [2]:
data=pd.read_csv('C:/Users/120761/Documents/PyScripts/multilinear2.csv')

In [11]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [14]:
data.experience=data.experience.fillna('zero')
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [16]:
(data.columns)

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [18]:
import math
median_test_score=math.floor(data['test_score(out of 10)'].mean())
median_test_score

7

In [21]:
data['test_score(out of 10)']=data['test_score(out of 10)'].fillna(median_test_score)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [23]:
data.experience=data.experience.apply(w2n.word_to_num)

In [24]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [27]:
X=data.iloc[:, :3]
X


experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [29]:
Y=data.iloc[:,-1]
Y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [32]:
X_train,X_test,Y_train,Y_test

(   experience  test_score(out of 10)  interview_score(out of 10)
 1           0                    8.0                           6
 7          11                    7.0                           8
 3           2                   10.0                          10
 0           0                    8.0                           9
 5           3                    7.0                          10
 4           7                    9.0                           6,
    experience  test_score(out of 10)  interview_score(out of 10)
 6          10                    7.0                           7
 2           5                    6.0                           7,
 1    45000
 7    80000
 3    65000
 0    50000
 5    62000
 4    70000
 Name: salary($), dtype: int64,
 6    72000
 2    60000
 Name: salary($), dtype: int64)

In [33]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [42]:
#1st method
regressor.predict([[2,9,6]])

array([53715.78077665])

In [43]:
regressor.predict([[12,10,10]])

array([96106.30680253])

In [34]:
#2nd method to


Y_pred=regressor.predict(X_test)

In [35]:
Y_pred

array([75610.57559901, 57496.5574222 ])

In [36]:
Y_test

6    72000
2    60000
Name: salary($), dtype: int64

In [37]:
from sklearn.metrics import r2_score
score=r2_score(Y_pred,Y_test)

In [38]:
score

0.8823380538584785

In [39]:
regressor.predict([[2,9,6]])

array([53715.78077665])

In [40]:
regressor.predict([[12,10,10]])

array([96106.30680253])

In [41]:
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000